### ISSUE TITLE
How to Get Events Published?

### ISSUE THREAD

**Issue by cbulock** [legrego/homeassistant-elasticsearch#11]
Installed this as I've been looking for a good solution on getting HASS logs into elasticsearch.

After installing the component, it created the index and alias, but I'm not getting any events published.  No errors are showing up, only things I see in the HASS logs are that the rollover succeeds whenever I restart HASS.

Is there some config that need to be setup to have the logs published?  Currently just setting the url and leaving the rest at defaults.

**Comment by vquiering** [comment]
Same here. I'm using version 0.74.2.
The index and template are created. No docs are published.

**Comment by legrego** [comment]
Hey @cbulock, @vquiering:

Thanks for giving this a spin! I'm working on getting this component updated so that it behaves in a more consistent manner. I modeled this after my [HomeSeer plugin](https://github.com/legrego/HSPI_Elasticsearch), but I think that was a poor choice given that the two systems have different eventing models. I'll diagnose this further over the next couple of days and respond back here.

**Comment by legrego** [comment]
@cbulock @vquiering 

I pushed a change that should hopefully fix the indexing problems you are seeing. You will need to remove the index template and any indices that the plugin may have created before trying the newest version.

If you get a chance, please run through the steps below and let me know if it helps!

1) Stop home-assistant
2) Run the following from Kibana's Dev Tools to remove the index template and any indices:
```
DELETE _template/hass-index-template
```

```
DELETE hass-events-*
```

3) Install updated plugin from `master`
4) Start home-assistant

**Comment by vquiering** [comment]
@legrego 
Events get published now. Thank you very much.

**Comment by cbulock** [comment]
Can confirm this is working for me now as well!  Thanks for the work put into this!
