### ISSUE TITLE
Defining phases using ILM

### ISSUE THREAD

**Issue by ankerstal** [legrego/homeassistant-elasticsearch#140]
Hi!

Its a problem that this integration overwrites the ILM-policy that is changed in elasticsearch. I have a short lived hot phase, and then a long warm phase on slower storange. But since this integration overwrites my policy all the time this does not work.

I would like to have one of two options:
  * Option to not overwrite policy if it exists.
  * Option to specify a full policy with multiple phases in configuration.

**Comment by legrego** [comment]
Hey @ankerstal, thanks for opening this issue. I intentionally took a simple/opinionated approach to ILM, due to the sheer number of available configuration options. I'm not personally interested in allowing a full policy specification, as Kibana does a much better job of presenting all of these options than this component ever could.

I'm not opposed to skipping policy overwrite, but I am curious: if you have your own policy needs, is there any benefit to this component defining its own policy? Would it be easier for you to turn off this component's ILM policy, so that it doesn't even attempt to create/recreate something that doesn't work for your needs?

**Comment by legrego** [comment]
I see there are a number of 👍 reactions to this issue. Can anyone weigh in on my questions above?

> I'm not opposed to skipping policy overwrite, but I am curious: if you have your own policy needs, is there any benefit to this component defining its own policy? Would it be easier for you to turn off this component's ILM policy, so that it doesn't even attempt to create/recreate something that doesn't work for your needs?
