### ISSUE TITLE
Make login attempts visible via Elasticsearch

### ISSUE THREAD

**Issue by sharbich** [legrego/homeassistant-elasticsearch#206]
Hello,
i would like to send the login attempts in Homeassistant to Elasticsearch. Which sensors from the logging would I have to use?
Greetings from Stefan Harbich

**Comment by legrego** [comment]
Hey @sharbich. I don't think Home Assistant exposes a sensor for this automatically. If it did, then this component would publish it by default. There are some pretty old discussions dating to the 0.x days, but I haven't found anything recent:

https://community.home-assistant.io/t/failed-login-detection/4280

I'm going to close this issue since it doesn't pertain to this component, but rather something within Home Assistant. Once you have a sensor established, we'd be happy to help ensure it is published to ES correctly.
