### ISSUE TITLE
Rename time field to @timestamp?

### ISSUE THREAD

**Issue by jakommo** [legrego/homeassistant-elasticsearch#38]
**Is your feature request related to a problem? Please describe.**
Currently the default time field is just called `time`. Logstash and Beats are using `@timestamp` by default and while there is no real need for this name, it's kind of the standard name for the default time field. 

Want to start a discussion on this and hear others opinions on this.

**Comment by legrego** [comment]
I'm certainly not opposed to this change. `@timestamp` is more consistent with the Elastic stack, so this makes sense to me.

If you (or anyone else) gets to this before me, I'd like to try to combine this with the fix for #32, so that we can take care of two breaking mapping changes at the same time. Either that or we can have two PRs up that we merge at the same time. That might be the smarter approach.
